### ISSUE TITLE
check-source-childs is not available and seems to be broken in main

### ISSUE THREAD

**Issue by slve** [Montreal-Analytics/dbt-gloss#38]
**Describe the bug**
check-source-childs is not available in v1.0.0 also seems to be broken in main

**To Reproduce**
1. Configure in .pre-commit-config.yaml
```
[...]
      - id: check-source-childs
        args: ["--min-child-cnt", "1", "--"]
```
2. run pre-commit
```
   pre-commit run --all-files
[ERROR] `check-source-childs` is not present in repository https://github.com/offbi/pre-commit-dbt.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```
3. run autoupdate
```
   pre-commit autoupdate                                                           1 ↵
Updating https://github.com/offbi/pre-commit-dbt ... Cannot update because the update target is missing these hooks:
check-source-childs
Updating https://github.com/sqlfluff/sqlfluff ... already up to date.
```
4. fork and tag, then update the pre-commit-config.yaml to point to forked latest tag
5. run pre-commit again
```
[...]
  File "[...]/.dots/cache/pre-commit/repop3elpxm3/py_env-python3.9/lib/python3.9/site-packages/pre_commit_dbt/utils.py", line 209, in get_source_schemas
    for source in schema.get("sources", []):
AttributeError: 'str' object has no attribute 'get'
```

**Expected behavior**
check-source-childs hook to be available and working in mainstream version

**Version:**
v1.0.0

**Comment by migueltp** [comment]
+1 on this

**Comment by jogomez97** [comment]
It looks like it was solved in #33, I've tested it locally and works as expected. Is any release planned soon?

**Comment by johnkangw** [comment]
I'm running on v1.1.0 but am experiencing the same problem as @slve with the AttributeError. Do you know if there is any resolution upcoming on this issue?

**Comment by JFrackson** [comment]
Ignore the noise above^^ I've just double checked this and it is still an issue on v1.1.0 and raises the following error:

```
AttributeError: 'str' object has no attribute 'get'
```

There's also another error that I encountered that is worth looking into more closely that occurs when trying to do a safe_load of a yaml file:

```
ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
```

**Comment by k0x2e** [comment]
`check-source-childs` was implemented and is available in the current release. Closing as completed — if you're still seeing the hook-not-found error, make sure you are pointing at `dbt-checkpoint/dbt-checkpoint` (not the old `offbi/pre-commit-dbt` repo) and run `pre-commit autoupdate`.
